GET http://localhost:3000/values

###

get http://localhost:3000/rigData

###

get http://localhost:3000/statuses

###

get http://localhost:3000/alarms


###
post http://192.168.1.116:1880/commands
Content-Type: application/json

{"commands":{"schedule":{"cmd_schedule_function":"add","cmd_schedule_start_time":1705399121357,"cmd_schedule_end_time":1705485521357,"cmd_schedule_recurrence":0,"cmd_schedule_value":0, "cmd_schedule_index" : 0}}}


###

GET http://192.168.1.116:1880/schedule

###

get http://localhost:3000/schedule

###


POST http://192.168.1.1/api/login
Content-Type: application/json

{"username": "admin", "password": "TurfpalDev1024"}

###

GET http://192.168.1.1/api/firmware/device/status
Content-Type: application/json
Authorization: Bearer 5fddeb5546d173017f361193bdb4afea


###

GET http://192.168.1.1/api/dhcp/leases/ipv4/status
Content-Type: application/json
Authorization: Bearer f0b8e9b8cf31ec3d4bc2eaad6cb97eac
